## NOT ALL CONFIGURATIONS ARE PROVIDED, ONLY PROVIDED VALUES OPEN FOR CHANGE PROVIDED
## Material Enum list provided, IT MUST be lower cast and MUST be a valid variant name
## https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

# Items that Elevators will ignore checking for.
# These items can be placed in the destination space.
# Remove/add any item you want. Use valid Material names and IDs.
# Ignore everything with: ignoreList: 'all'
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
ignoreList: 'air, torch, wall_torch, redstone_torch_on, redstone_torch_off, redstone_wall_torch, vine, lever, banner, stone_button, wood_button, oak_button, spruce_button, birch_button, jungle_button, acacia_button, dark_oak_button, sign, sign_post, wall_sign, oak_sign, oak_wall_sign, spruce_sign, spruce_wall_sign, birch_sign, birch_wall_sign, jungle_sign, jungle_wall_sign, acacia_sign, acacia_wall_sign, dark_oak_sign, dark_oak_wall_sign, yellow_carpet, green_carpet, light_blue_carpet, white_carpet, orange_carpet, magenta_carpet, lime_carpet, pink_carpet, light_gray_carpet, black_carpet, red_carpet, brown_carpet, blue_carpet, purple_carpet, gray_carpet, cyan_carpet'


